id: I6C5EF2BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T01:01:35+00:00'
last_modified: '2022-06-07T12:27:47.487349+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16571
  title: འཁྲུངས་གླིང་མེ་ཏོག་ར་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    ABEB:
      image_group_id: I1KG22746
      title: ''
      total_pages: 324
      order: 1
      base_file: ABEB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
