id: P000617
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16571
  title: འཁྲུངས་གླིང་མེ་ཏོག་ར་བ།
  author: ''
  volumes:
    3ae41f2dd0cd4205bcfa17a5055c07a7:
      image_group_id: I1KG22746
      title: ''
      volume_number: 1
      total_pages: 324
